services:
  api:
    build: .
    env_file:
      - /ChallengeProject/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/challenge-globant
      - backup_volume:/var/lib/backups
    command: sh -c "ls -la /challenge-globant && echo 'Checking for entrypoint' && find / -name entrypoint.sh"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employee_db
      - DATABASE_URL=postgresql://postgres:password@db:5432/employee_db
      - MAX_BATCH_SIZE=1000
      - BACKUP_DIR=/var/lib/backups
    restart: always
    

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql:ro   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employee_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  backup_volume: